name: Release - Module

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 1.0.0

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/module-release.yaml@main
    with:
      packages: codbex-assets-reports
      packages-build: codbex-assets-reports
      release-version: ${{ inputs.release-version }}
      release-content: |
        ## codbex-assets-reports - ${{ inputs.release-version }}
        
        Assets Reports Management Module
        
        ## Installation
        
        ```
        npm install @codbex/codbex-assets-reports@${{ inputs.release-version }}
        ```
        
        ## Access points:
        
        - N/A
    secrets: inherit